# Numpy Basic <hr style="border:2.5px solid #126782"></hr>

<b>Mark Andrei V. Tico</b>
<br>CpE 2A

In [14]:
# imports and packages
import numpy as np

# 1D Array

In [15]:
my_array =[1,2,3]

In [16]:
type(my_array)

list

In [17]:
my_array = np.array([1,2,3])

In [18]:
np.shape(my_array)

(3,)

# 2D Array

In [19]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
trans_array = my_array.T

In [21]:
np.shape(trans_array)

(3, 2)

In [22]:
np.sum(trans_array,axis=0)

array([ 6, 15])

In [23]:
np.sum(trans_array,axis=1)

array([5, 7, 9])

# Measure of Central Tendency

In [24]:
resistance = np.array([
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8], #Jaguar
    [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan], #Panther
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [25]:
np.nanmean(resistance,axis=1)

array([ 9.4 , 10.75])